language: python
python:
  - "3.4"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python3-pyqt5 python3-pytest  python3-pip
  - sudo pip3 install pytest-qt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - cd src/pesel2pbn && py.test tests.py
