language: python
python:
  - "3.4"
before_install:
  - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtdeclarative5-dev unzip python3-dev 
  - wget http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.8/sip-4.16.8.zip
  - unzip sip-4.16.8.zip
  - cd sip-4.16.8 && python3 configure.py && sudo make install
  
  - sudo apt-get install -y python3-pyqt5 python3-pytest  python3-pip
  - sudo pip3 install pytest-qt
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - cd src/pesel2pbn && py.test tests.py
